---
title: Publications
csl: apa-cv.csl
bibliography: references.bib
suppress-bibliography: true
link-citations: false
citations-hover: false
---

## Peer reviewed publications

-   @AgendaSetting2025 ([<i class="fas fa-file-pdf"></i> Manuscript](/pdfs/RichardsonEtAl_2025_AgendaSetting.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/7t4v2/files/osfstorage))

-   @HerdingCats2025 ([<i class="fas fa-file-pdf"></i> PDF](/pdfs/RichardsonEtAl_2025_HerdingCats.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/d7szc/files/osfstorage))

-   @Viruses2024 ([<i class="fas fa-file-pdf"></i> PDF](/pdfs/MenendezRichardsonEtAl_2024_Viruses.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/h4c26/files/osfstorage))

-   @GroupsCrowds2022 ([<i class="fas fa-file-pdf"></i> PDF](/pdfs/RichardsonKeil_2022_EffectiveReasoning.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/6pw5n/files/osfstorage))

-   @ThinkingTakesTime2022 ([<i class="fas fa-file-pdf"></i> PDF](/pdfs/RichardsonKeil_2022_ThinkingTakesTime.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/z6ykt/files/osfstorage))

-   @Scaffolding2021 ([<i class="fas fa-file-pdf"></i> PDF](/pdfs/RichardsonEtAl_2021_Scaffolding.pdf) \| [<i class="fab fa-github"></i> code & data](https://osf.io/epk4b/files/osfstorage))

<!--
## Working papers

- @pfanderQuasiuniversalAcceptanceBasic2024 (*submitted*)
- @pfanderTrustingForgettingImpressive2025 (*submitted*)
- @pfanderFrenchTrustMore2025
-->

## Conference Proceedings

-   @pfanderHowWiseCrowd2024([<i class="fas fa-file-pdf"></i> pdf](pdfs/how_wise_is_crowd.pdf) \| [<i class="fa-solid fa-person-chalkboard"></i>poster](talks/cogsci_2024.pdf) \| [<i class="fab fa-github"></i> code & data](https://github.com/janpfander/consensus_trust.git))


## Talks

-   Pfänder, J., & Mercier, H. (2025, March). *Trust in science*. Paris School of International Affairs (Sciences Po), Paris.

-   Pfänder, J., & Altay, S. (2025, March). *Spotting False News and Doubting True News. A Meta-Analysis of News Judgments*. Infox sur seine, Paris.

-   Pfänder, J. (2024, July). *How wise is the crowd: Can we infer people are accurate and competent merely because they agree with each other?* 46th Annual Meeting of the Cognitive Science Society, Rotterdam.

-   Pfänder, J. (2024, June). *Processus sous-tendant la confiance dans la science.* 5ème édition des Rencontres Jeunes Chercheur·euse·s, Grenoble.

-   Pfänder, J., & Altay, S. (2024, February). *Spotting False News and Doubting True News: A Meta-Analysis of News Judgments.* EDMO Scientific Conference on Disinformation, Amsterdam.


